# This is a basic workflow to help you get started with Actions

name: Discord YT

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push]
  # schedule:
  #   - cron: 0 */6 * * *

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        # Semantic version range syntax or exact version of a Python version
        python-version: '3.8.2' 
    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      env:
        YT: ${{ secrets.YT_TAALAM }}
        DC: ${{ secrets.DC_KOKKEM }} 
      run: |
        python -m pip install --upgrade pip
        pip install requests
        python script.py
    - name: push
      uses: github-actions-x/commit@v2.6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        push-branch: 'master'
        commit-message: 'update YT.json'
        force-add: 'true'
        files: YT.json
        name: Github Actions
        email: mukskashyap.de@gmail.com